/**
 * Domain Models
 * 
 * TypeScript interfaces defining the data structures used throughout the app.
 * These match the API response/request formats.
 * 
 * Benefits:
 * - Type safety: Compile-time checks prevent errors
 * - IntelliSense: Auto-completion in IDE
 * - Documentation: Clear contract for data shape
 */

/**
 * Video Game Entity
 * Main domain object representing a video game
 */
export interface VideoGame {
  id: number;              // Unique identifier (generated by backend)
  title: string;           // Game title
  description: string;     // Game description/summary
  releaseDate: string;     // ISO date string (yyyy-MM-dd)
  genre: Genre;            // Related genre entity
  publisher: Publisher;    // Related publisher entity
  developer: Developer;    // Related developer entity
}

/**
 * Genre Lookup
 * Classification category for games (Action, RPG, etc.)
 */
export interface Genre {
    id: number;
    name: string;
}

/**
 * Publisher Lookup
 * Company that publishes the game
 */
export interface Publisher {
    id: number;
    name: string;
}

/**
 * Developer Lookup
 * Company/team that develops the game
 */
export interface Developer {
    id: number;
    name: string;
}
