/**
 * NgRx Actions
 * 
 * Actions are dispatched throughout the app to trigger state changes.
 * Using createAction provides type safety and reduces boilerplate.
 * 
 * Action Flow:
 * Component -> dispatch(action) -> Reducer (sync state change)
 *                               -> Effect (async side effect) -> dispatch(success/failure action)
 */
import { createAction, props } from '@ngrx/store';
import { VideoGame } from '../models/video-game.model';

// Load Games Actions - Fetch all games from API
export const loadGames = createAction('[Games] Load Games');
export const loadGamesSuccess = createAction(
  '[Games] Load Games Success', 
  props<{ games: VideoGame[] }>() // Payload: array of games from API
);
export const loadGamesFailure = createAction(
  '[Games] Load Games Failure', 
  props<{ error: any }>() // Payload: error object for logging
);

// Add Game Actions - Create new game
export const addGame = createAction(
  '[Games] Add Game', 
  props<{ game: Partial<VideoGame> }>() // Partial: ID generated by backend
);
export const addGameSuccess = createAction(
  '[Games] Add Game Success', 
  props<{ game: VideoGame }>() // Complete game object from API response
);
export const addGameFailure = createAction(
  '[Games] Add Game Failure', 
  props<{ error: any }>()
);

// Update Game Actions - Modify existing game
export const updateGame = createAction(
  '[Games] Update Game', 
  props<{ game: VideoGame }>() // Full game object with ID
);
export const updateGameSuccess = createAction(
  '[Games] Update Game Success', 
  props<{ game: VideoGame }>() // Updated game from API
);
export const updateGameFailure = createAction(
  '[Games] Update Game Failure', 
  props<{ error: any }>()
);

// Delete Game Actions - Remove game by ID
export const deleteGame = createAction(
  '[Games] Delete Game', 
  props<{ id: number }>() // Only ID needed for deletion
);
export const deleteGameSuccess = createAction(
  '[Games] Delete Game Success', 
  props<{ id: number }>() // ID of deleted game for state update
);
export const deleteGameFailure = createAction(
  '[Games] Delete Game Failure', 
  props<{ error: any }>()
);
